Начальный уровень. Удаленные действия. Задание 1
yeeeyoooduck/globexit_adaptation pull request #11
Opened 2024-08-05 16:23 UTC by yeeeyoooduck

2024-08-14 10:49 UTC, xKit-22 requested changes

2024-08-14 10:49 UTC, xKit-22 commented on src/remote_actions/remote_actions_task1.ts
> +		tools.create_notification(Int("6423292989894653736"), curUserID, message)
Выносим id в переменные шаблона

2024-08-28 11:43 UTC, yavabit approved these changes

2024-08-29 16:14 UTC, xKit-22 approved these changes

2024-08-29 16:14 UTC, merged