Продвинутый уровень. API. Задание №1
yeeeyoooduck/globexit_adaptation pull request #18
Opened 2024-09-01 08:21 UTC by yeeeyoooduck

2024-09-02 08:40 UTC, xKit-22 approved these changes

2024-09-02 12:09 UTC, yavabit requested changes

2024-09-02 12:09 UTC, yavabit commented on api/task1/backend/src/modules/collaborators.ts
> +		const collaborators = ParseJson(response.Body)
добавить проверку кода ответа, проверку наличия Body

2024-09-02 12:09 UTC, yavabit commented on api/task1/frontend/src/components/Collaborators.tsx
- состояние загрузки
- проверка на данные

2024-09-03 11:26 UTC, yavabit approved these changes

2024-09-04 11:00 UTC, merged