Продвинутый уровень. API. Задание №3
yeeeyoooduck/globexit_adaptation pull request #20
Opened 2024-09-01 08:22 UTC by yeeeyoooduck

2024-09-02 08:42 UTC, xKit-22 approved these changes

2024-09-02 12:14 UTC, yavabit requested changes

2024-09-02 12:14 UTC, yavabit commented on api/task3/collaborators.js
> +        return "Successfully added";
- проверки на поля
- Trim
- doc.TopElem.{field}.Value
- return в случае неуспешного ответа

прим:
```
if(collaborator.login == '' || collaborator.login) {
bError = true;
sMessage += "Не удалось полчуть логин сотрудника\n"
}
if(collaborator.password== '' || collaborator.password) {
bError = true;
sMessage += "Не удалось полчуть пароль сотрудника\n"
}

if(bError) { return sMessage }
```

2024-09-02 12:16 UTC, yavabit commented on api/task3/collaborators.js
> +        return "Successfully added";
если это например обязательные поля, то проверяем еще и на '' пустую строку

2024-09-03 11:27 UTC, yavabit approved these changes

2024-09-04 11:23 UTC, merged