Продвинутый уровень. Библиотеки программного кода. Задание №1
yeeeyoooduck/globexit_adaptation pull request #22
Opened 2024-09-04 11:28 UTC by yeeeyoooduck

2024-09-05 07:56 UTC, xKit-22 requested changes

2024-09-05 07:56 UTC, xKit-22 commented on library/src/library.ts
1. Давай уберем отовсюду пароли

2024-09-05 07:56 UTC, xKit-22 commented on library/src/library.ts
> +	} catch (error) {
Если уберешь пароль, то можно будет обойтись запросом, вместо открытия документа

2024-09-05 07:56 UTC, xKit-22 commented on library/src/library.ts
> +		newCollaboratorDocument.TopElem.middlename.Value = collaborator.middlename;
newCollaboratorDocument.TopElem можно выносить в отдельную переменную
teNewCollaborator

2024-09-05 07:56 UTC, xKit-22 commented on library/src/library.ts
> +		return newCollaboratorDocument.TopElem.id;
Можно использовать newCollaboratorDocument.DocID

2024-09-05 07:56 UTC, xKit-22 commented on library/src/agent.ts
> +	agentId: "agents_task1"
id агента

2024-09-06 09:53 UTC, xKit-22 approved these changes

2024-09-06 10:10 UTC, yavabit approved these changes

2024-09-06 10:15 UTC, merged