Начальный уровень. Настраиваемые web-шаблоны. Задание №3
yeeeyoooduck/globexit_adaptation pull request #3
Opened 2024-07-17 05:29 UTC by yeeeyoooduck

2024-07-17 15:12 UTC, xKit-22 requested changes

2024-07-18 07:46 UTC, yavabit requested changes
+ хромает структура фронта и бека
+ ряд вопросов по типизации
+ ошибки подсвечиваемые ts и eslint не должны игнорироваться

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/backend/README.md
md файл должен содержать описание задания и инструкцию по сборке приложения

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/backend/src/example.ts
> +type Subscription = {
+ должен быть в том файле, где используется
+ для наглядности можно добавлять импорты и экспорты, они удалятся при транспиляции

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/backend/src/modules/collaborators.ts
> +import { file_sources } from "@umbrik/webtutor-types/lib/global_catalogs"
зачем здесь?

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/backend/src/modules/collaborators.ts
> +	const xml_collaborator = tools.open_doc(collaborator.id)
+ именование переменных в camelCase -- collaboratorDoc

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/backend/src/modules/collaborators.ts
> +	return {'history_states': history_states, 'change_logs': change_logs}
тестировалось? все состояния подтянутся таким образом?

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/backend/src/modules/collaborators.ts
> +	te_subscription.type = 'blog'
почему 'blog'? У нас подписка с человека на человека. collaborator

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/backend/src/modules/collaborators.ts
> +	te_subscription.person_id.sd.org_name = collaborator.org_name
достаточно добавления person_id, остальные данные должны подтянуться автоматически. Тогда getUserInfo функция будет не нужна

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/backend/src/modules/collaborators.ts
> +function addSubscription(user_id: string) {
обернуть тело функции в try/catch

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/backend/src/modules/collaborators.ts
обратить внимание на ошибку ts -- Property 'type' does not exist on type 'XmlTopElem'. Did you mean 'Type'?ts(2551). Док должен быть без ошибок

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/backend/src/modules/collaborators.ts
> +	te_subscription.type = 'blog'
можно создать тестовую подписку вручную в админке и посмотреть ее xml документ

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/backend/src/modules/collaborators.ts
> +	let team = [];
const

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/backend/src/modules/collaborators.ts
> +	for (subscription in subscriptions) {
достаточно одного sql запроса было бы, чтоб не лезть в цикл

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/backend/src/modules/collaborators.ts
часть функций не соответствует логике их нахождения в этом модуле

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/backend/src/utils/type.ts
+ все ли из этого используется? Если ничего, то удалить файл

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/frontend/.gitignore
можно вынести один общий gitignore для бека и фронта

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/frontend/README.md
аналогично редме в беке

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/frontend/index.html
> +    <title>Vite + React + TS</title>
сменить title

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/frontend/index.html
> +    <div id="root"></div>
в root лучше добавлять номер требования или задачи или какой то др идентификатор, Для того случая, когда к одной странице может быть привязано несколько реакт шаблонов, чтобы не словить конфликт

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/frontend/package.json
можно было бы использовать различные ui библиотеки по согласованию, для ускорения разработки

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/frontend/src/App.css
> +.cards-card {
бэм

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/frontend/src/common.css
чем common.css отличается логически от App.css и от index.css. Для чего нам на фронте 3 css файла?

2024-07-18 07:46 UTC, yavabit commented on entry_level/web_template/task3/frontend/vite.config.ts
> +    base: isProduction ? '/adaptation/collaborators/frontend' : '/',
приложение проверялось в системе webSoft, переносилось туда полностью? Не с локальным запуском react , а с чанками реакт

2024-08-29 06:53 UTC, xKit-22 requested changes

2024-08-29 06:53 UTC, xKit-22 commented on entry_level/web_template/task3/backend/src/modules/collaborators.ts
> +}
В  этой и последующих функкциях: Функции selectAll и selectOne прописаны с дженериком, нужно прописать в него тип. тк возвращаемый тип такой же, из функции тип можно убрать

2024-08-29 06:53 UTC, xKit-22 commented on entry_level/web_template/task3/frontend/src/components/App.tsx
> +      fetchUserInfo(user_id)
camelCase

2024-08-29 06:53 UTC, xKit-22 commented on entry_level/web_template/task3/frontend/src/components/App.tsx
> +
объединить в один useEffect

2024-08-29 06:53 UTC, xKit-22 commented on entry_level/web_template/task3/frontend/src/components/App.tsx
> +
Дублирование кода

2024-08-29 06:53 UTC, xKit-22 commented on entry_level/web_template/task3/frontend/src/components/Tabs.tsx
Дубирование кнопок. Нужно сделать один компонент

2024-08-29 06:53 UTC, xKit-22 commented on entry_level/web_template/task3/frontend/src/components/App.tsx
Само тела табов, которые обернуты в main тоже должны быть отдельными компонентами + дублируется header в двух последних табах

2024-08-29 06:54 UTC, xKit-22 commented on entry_level/web_template/task3/backend/src/modules/collaborators.ts
> +function addSubscription(user_id: string) {
Остальных тоже

2024-08-29 08:58 UTC, yavabit requested changes
+ Просмотреть все незакрытые комментарии

2024-08-29 08:58 UTC, yavabit commented on entry_level/web_template/task3/backend/src/modules/collaborators.ts
> +function getDetails(userId: string) {
try catch ?

2024-08-29 08:58 UTC, yavabit commented on entry_level/web_template/task3/backend/src/modules/collaborators.ts
> +		Response.Write(errorObject.GetOptProperty("message", error));
throw Error

2024-08-29 08:58 UTC, yavabit commented on entry_level/web_template/task3/backend/src/index.ts
> +}
вынести

2024-08-29 08:58 UTC, yavabit commented on entry_level/web_template/task3/frontend/src/components/App.tsx
почему App.tsx в компонентах лежит? он переиспользуется где то?

2024-08-29 16:03 UTC, xKit-22 commented on entry_level/web_template/task3/frontend/src/components/App.tsx
Дропнула случайно комм Антона о том, что App.tsx нужно вынести из components

2024-08-30 14:50 UTC, xKit-22 approved these changes

2024-09-02 08:33 UTC, yavabit approved these changes

2024-09-02 08:39 UTC, merged