Начальный уровень. Агенты. Задание №1
yeeeyoooduck/globexit_adaptation pull request #4
Opened 2024-07-17 19:03 UTC by yeeeyoooduck

2024-07-19 09:11 UTC, xKit-22 requested changes

2024-07-19 09:11 UTC, xKit-22 commented on entry_level/agents/task1/agnt_task1.js
Пишем все на ts
Посмотри еще раз структуру агента из примера. 
Добавь логирование через функцию Log, посмотри правильное оформление  первого и последнего информационных логов.

2024-07-19 09:11 UTC, xKit-22 commented on entry_level/agents/task1/agnt_task1.js
> +        var newPassword = tools.random_string(8);
Ненужная переменная

2024-08-14 08:04 UTC, xKit-22 requested changes

2024-08-14 08:04 UTC, xKit-22 commented on entry_level/src/agents/agnt_task1.ts
> +	let employeeDoc;
Переменная не изменяется, лучше const

2024-08-14 08:41 UTC, xKit-22 commented on entry_level/src/agents/agnt_task1.ts
> +		if (employeeDoc) {
Лучше указывать проверку на undefined явно

2024-08-14 13:09 UTC, yavabit commented on entry_level/src/agents/agnt_task1.ts
> +log("----------------Конец. Globexit. Агент для установки случайных паролей------------------");
timer убираем, try catch в этом месте убираем.

2024-08-14 13:09 UTC, yavabit commented on entry_level/src/agents/agnt_task1.ts
> +	agentId: ""
id агента

2024-08-28 10:53 UTC, xKit-22 commented on entry_level/src/agents/agnt_task1.ts
> +	agentId: "agents_task1"
id агента, а не код агента

2024-08-28 11:36 UTC, yavabit approved these changes

2024-08-29 08:08 UTC, xKit-22 approved these changes

2024-08-29 08:40 UTC, merged