Начальный уровень. Агенты. Задание №2
yeeeyoooduck/globexit_adaptation pull request #5
Opened 2024-07-18 11:26 UTC by yeeeyoooduck

2024-07-19 09:12 UTC, xKit-22 requested changes

2024-07-19 09:12 UTC, xKit-22 commented on entry_level/agents/task2/agnt_task2.js
Пишем все на ts
Посмотри еще раз структуру агента из примера. 
Добавь логирование через функцию Log, посмотри правильное оформление  первого и последнего информационных логов.
Придерживайся единого стиля в наименовании переменных - camelCase.

2024-08-14 08:39 UTC, xKit-22 requested changes

2024-08-14 08:39 UTC, xKit-22 commented on entry_level/src/agents/agnt_task2/agnt_task2.ts
> +		newDocument = tools.new_doc_by_name<XmlDocument>("document");
Тип DocumentDocument

2024-08-28 11:02 UTC, xKit-22 approved these changes

2024-08-28 11:37 UTC, yavabit approved these changes

2024-08-28 11:51 UTC, merged