Начальный уровень. Агенты. Задание №3
yeeeyoooduck/globexit_adaptation pull request #6
Opened 2024-07-24 12:50 UTC by yeeeyoooduck

2024-07-30 07:59 UTC, xKit-22 commented on src/agents/agnt_task1.ts
> +		employeeDoc = tools.open_doc(OptInt(employeeId));
не указан тип открываемого документа

2024-07-30 08:05 UTC, xKit-22 requested changes

2024-07-30 08:05 UTC, xKit-22 commented on src/agents/agnt_task1.ts
> +		employeeDoc.TopElem.password = tools.random_string(8);
Нет проверки документа на undefined

2024-07-30 08:05 UTC, xKit-22 commented on src/agents/agnt_task1.ts
> +	else alert(payload)
Посмотри обновленный пресет по агентам, исправили функцию логирования. Это условие не имеет смысла, т.к. специально создаем функцию, чтобы она не засоряла логи, если переменная is_debug выключена

2024-07-30 08:07 UTC, xKit-22 commented on src/agents/agnt_task2/agnt_task2.ts
> +		newDocument = tools.new_doc_by_name("document");
Тип документа не указан

2024-07-30 08:20 UTC, xKit-22 requested changes

2024-07-30 08:20 UTC, xKit-22 commented on src/agents/agnt_task2/agnt_task2.ts
> +		newDocument = tools.new_doc_by_name("document");
Тип документа не указан

2024-07-30 08:20 UTC, xKit-22 commented on src/agents/agnt_task2/agnt_task2.ts
> +		newDocument = tools.new_doc_by_name("document");
Тип документа не указан

2024-07-30 08:20 UTC, xKit-22 commented on src/agents/agnt_task2/agnt_task2.ts
> +	else alert(payload)
Тоже поправь тут условие по новому пресету

2024-07-30 08:20 UTC, xKit-22 commented on src/agents/agnt_task2/agnt_task2.ts
> +		newDocumentTE.parentDocumentId = chapter.parentDocumentId;
у объекта нет полей createDate и parentDocumentId, есть create_date и parent_document_id. Когда ты обращаешься к полям объекта - нужно смотреть их наименование в xml документе. Правило именования camelCase распространяется на твои переменные

2024-07-30 10:14 UTC, yeeeyoooduck commented on src/agents/agnt_task2/agnt_task2.ts
> +		newDocumentTE.parentDocumentId = chapter.parentDocumentId;
Похоже, что когда я поправлял все на camelCase, я случайно задел

2024-08-14 10:03 UTC, xKit-22 requested changes

2024-08-14 10:03 UTC, xKit-22 commented on src/agents/agnt_task3/agnt_task3.ts
> +
Много лишних действий. 
Находим сотрудника, если такой есть, то просто обновляем должность (так же проверяем должность, если нет - создаем), если сотрудника нет - создаем и записываем должность. Бзе проверок. Можно использовать функцию obtain_doc_by_key. Возвращает документ, если он есть, если нет, то создает.

2024-08-28 11:38 UTC, yavabit approved these changes

2024-09-02 10:44 UTC, merged