Начальный уровень. Выборки. Задание №1
yeeeyoooduck/globexit_adaptation pull request #9
Opened 2024-07-30 10:12 UTC by yeeeyoooduck

2024-08-14 10:25 UTC, yeeeyoooduck commented
f

2024-08-14 10:41 UTC, xKit-22 commented on src/selections/selection_task1.ts
> +	return selectAll(query) as ResultObject[];
Функция не испортирована

2024-08-14 10:47 UTC, xKit-22 commented on src/selections/selection_task1.ts
> +	return selectAll(query) as ResultObject[];
Функции сейчас нет в файле

2024-08-28 11:41 UTC, yavabit requested changes

2024-08-28 11:41 UTC, yavabit commented on build/selections/selection_task1.js
> +          )";
запрос переделать, вложенные запросы с xquery отрицательно влияют на скорость. Попробуй через cte.

2024-08-28 14:01 UTC, xKit-22 commented on src/selections/selection_task1.ts
> +	return ArraySelectAll(XQuery(query)) as ResultObject[];
Тип указываем как дженерик функции ArraySelectAll

2024-08-30 09:27 UTC, xKit-22 approved these changes

2024-08-30 10:55 UTC, yavabit approved these changes

2024-08-30 12:06 UTC, merged